# Generated by Django 2.2.7 on 2019-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.TextField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('TPU', 'TPU')])),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shop', models.TextField()),
                ('url', models.URLField()),
                ('owner', models.TextField()),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
