# Generated by Django 2.2 on 2019-11-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0002_filament_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filament',
            name='amount',
            field=models.FloatField(),
        ),
    ]
