# Generated by Django 2.2 on 2019-11-16 18:15

from django.db import migrations, models
import django.db.models.deletion
import print3d.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filament', '0003_auto_20191117_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('amount', models.FloatField()),
                ('memo', models.TextField()),
                ('image_file', models.ImageField(upload_to=print3d.models.get_print3d_image_upload_path)),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament.Filament')),
            ],
        ),
    ]
