# Generated by Django 2.2 on 2019-11-16 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('print3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='print3d',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print3d',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
